/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mineriadedatos;

import java.util.logging.Level;
import java.util.logging.Logger;
import weka.classifiers.bayes.NaiveBayes;
import weka.core.DenseInstance;
import weka.core.converters.ConverterUtils.DataSource;
import weka.core.Instance;
import weka.core.Instances;
import weka.filters.Filter;
import weka.filters.unsupervised.attribute.Remove;

/**
 *
 * @author BRAYAN
 */
public class MineriaDeDatosForm extends javax.swing.JFrame {

    /**
     * Creates new form MineriaDeDatosForm
     */
    DataSource ds;
    Instances ins;
    NaiveBayes nb;

    public MineriaDeDatosForm() throws Exception {

        initComponents();
        this.setSize(670, 650); // Ancho: 800px, Alto: 600px
        // Centrar la ventana
        this.setLocationRelativeTo(null);
        // Evitar que el usuario redimensione la ventana
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setText("CALCULATOR OF PROBABILITY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 200, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel3.setText("Duration in month.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no credits/all paid", "all paid", "existing paid", "delayed previously", "critical/other existing credit" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel4.setText("Credit history.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "new car", "used car", "furniture/equipment", "radio/tv", "domestic appliance", "repairs", "education", "vacation", "retraining", "business", "other" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel5.setText("Purpose.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel6.setText("Credit amount.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel7.setText("Savings account/bonds. ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<100", "100<=X<500", "500<=X<1000", ">=1000", "no known savings" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel8.setText("Present employment since. ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 20));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<1", "1<=X<4", "4<=X<7", ">=7", " " }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 160, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel9.setText("Installment rate in percentage of disposable income . ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 320, 20));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 160, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel11.setText("Other debtors / guarantors");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "co applicant", "guarantor" }));
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 160, -1));

        jLabel13.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel13.setText("Property");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "real estate", "life insurance", "car", "no known property" }));
        getContentPane().add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 160, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel14.setText("Age in years");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 160, -1));

        jLabel15.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel15.setText("Other installment plans");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bank", "stores", "none" }));
        getContentPane().add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 160, -1));

        jLabel16.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel16.setText("Housing");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rent", "own", "for free" }));
        getContentPane().add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 160, -1));

        jLabel17.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel17.setText("Number of existing credits at this bank");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 160, -1));

        jLabel18.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel18.setText("Job");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unemp/unskilled non res", "unskilled resident", "skilled", "high qualif/self emp/mgmt" }));
        getContentPane().add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 160, -1));

        jLabel21.setFont(new java.awt.Font("Rockwell Condensed", 1, 13)); // NOI18N
        jLabel21.setText("Foreign worker");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no", " " }));
        getContentPane().add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 160, -1));

        jLabel22.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 620, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            ds = new DataSource("src\\mineriadedatos\\credit.g.arff");
        } catch (Exception ex) {
            Logger.getLogger(MineriaDeDatosForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ins = ds.getDataSet();
            ins.setClassIndex(ins.numAttributes() - 1);
            Remove remove = new Remove();
            remove.setAttributeIndices("1,9,11,18,19"); // Eliminar el primer atributo
            remove.setInputFormat(ins);
            Instances filteredIns = Filter.useFilter(ins, remove);
            ins = filteredIns;
            System.out.println(ins);
            nb = new NaiveBayes();
            nb.buildClassifier(ins);
        } catch (Exception ex) {
            Logger.getLogger(MineriaDeDatosForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Instance nuevo = new DenseInstance(ins.numAttributes());
            nuevo.setDataset(ins);

           // nuevo.setValue(0, (String) jComboBox18.getSelectedItem());
            nuevo.setValue(0, Double.parseDouble((String) jComboBox1.getSelectedItem()));
            nuevo.setValue(1, (String) jComboBox2.getSelectedItem());
            nuevo.setValue(2, (String) jComboBox3.getSelectedItem());
            nuevo.setValue(3, Double.parseDouble(jTextField2.getText()));
            nuevo.setValue(4, (String) jComboBox4.getSelectedItem());
            nuevo.setValue(5, (String) jComboBox5.getSelectedItem());
            nuevo.setValue(6, Double.parseDouble((String) jComboBox6.getSelectedItem()));
            //nuevo.setValue(7, (String) jComboBox7.getSelectedItem());
            nuevo.setValue(7, (String) jComboBox8.getSelectedItem());
            //nuevo.setValue(8, Double.parseDouble(jTextField3.getText()));
            nuevo.setValue(8, (String) jComboBox9.getSelectedItem());
            nuevo.setValue(9, Double.parseDouble(jTextField4.getText()));
            nuevo.setValue(10, (String) jComboBox10.getSelectedItem());
            nuevo.setValue(11, (String) jComboBox11.getSelectedItem());
            nuevo.setValue(12, Double.parseDouble((String) jComboBox12.getSelectedItem()));
            nuevo.setValue(13, (String) jComboBox13.getSelectedItem());
            //nuevo.setValue(14, Double.parseDouble((String) jComboBox14.getSelectedItem()));
            //nuevo.setValue(16, (String) jComboBox15.getSelectedItem());
            nuevo.setValue(14, (String) jComboBox16.getSelectedItem());
            System.out.println(nuevo);
            // Obtener probabilidades
            double probabilidades[] = nb.distributionForInstance(nuevo);
            double probabilidadBad = probabilidades[1];
            double umbral = 0.45;

            // Mostrar resultados
            if (probabilidadBad > umbral) {
                jLabel22.setText("Cliente rechazado, probabilidad de " + String.format("%.2f", probabilidadBad * 100) + "% de incumplir con sus cuotas.");
            } else {
                jLabel22.setText("Cliente aceptado, probabilidad de " + String.format("%.2f", (1 - probabilidadBad) * 100) + "% de cumplir con sus cuotas.");
            }
        } catch (NumberFormatException e) {
            jLabel22.setText("Error: Por favor, ingrese valores numéricos válidos.");
        } catch (Exception e) {
            jLabel22.setText("Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MineriaDeDatosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MineriaDeDatosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MineriaDeDatosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MineriaDeDatosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MineriaDeDatosForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MineriaDeDatosForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
